name: remoteadminplus

services:
  postgres:
    image: postgres:18
    volumes:
      - postgres-data:/var/lib/postgresql
      - app_data:/data
      - postgres-socket:/var/run/postgresql
      - ./initrunner.sh:/docker-entrypoint-initdb.d/initrunner.sh:ro
    restart: always
    environment:
      POSTGRES_PASSWORD: "thisshouldntmatterbecauseitsnotpubliclyaccessible"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 10

  traefik:
    image: traefik:v3.4
    restart: always
    command:
      - "--providers.docker=true"
      - "--api.insecure=true"
      - "--entrypoints.web.address=:8080"
      - "--entrypoints.traefik.address=:8081"
      - "--entryPoints.web.forwardedHeaders.trustedIPs=127.0.0.1/32"
    ports:
      - "8778:8080"
      - 8081:8081
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  api:
    depends_on:
      postgres:
        condition: service_healthy
    build: &build
      context: .
      args:
        SERVER_API_URL: http://api:3000/api
        URL: http://localhost:8080
    restart: on-failure
    user: runner
    environment: &env
      - DB_USER=runner
      - HOST=0.0.0.0
      - NODE_ENV=production
      - DATABASE_HINT=/var/run/postgresql
      - SERVER_API_URL=http://api:3000
      - DATA_DIR=/data
      - PROTOCOL_HEADER=x-forwarded-proto
      - HOST_HEADER=x-forwarded-host
    working_dir: /app/backend
    command: ["bun", "run", "start"]
    volumes:
      - app_data:/data
      - postgres-socket:/var/run/postgresql
    expose:
      - "3000"
    labels:
      - "traefik.http.routers.api.priority=100"
      - "traefik.http.routers.api.rule=PathPrefix(`/api`)"
    post_start:
      - command: chown -R runner:runner /data
        user: root

  website:
    depends_on:
      api:
        condition: service_started
    build: *build
    restart: on-failure
    environment: *env
    working_dir: /app/website
    command: ["bun", "--bun", "./build"]
    expose:
      - "3000"
    labels:
      - "traefik.http.routers.website.rule=PathPrefix(`/`)"

volumes:
  postgres-data:
  app_data:
  postgres-socket:
