name: remoteadminplus

services:
  postgres:
    image: postgres:18
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - app_data:/data
      - postgres-socket:/var/run/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 1s
      timeout: 5s
      retries: 10
    post_start:
      - command: useradd -m runner
        user: root
      - command: psql -U ${DB_USER} -d ${DB_NAME} -c "CREATE ROLE IF NOT EXISTS runner; CREATE DATABASE runner OWNER runner;"
        user: postgres

  valkey:
    image: valkey/valkey:8-alpine

  traefik:
    image: traefik:v3.4
    command:
      - "--providers.docker=true"
      - "--api.insecure=true"
      - "--entrypoints.web.address=:8080"
      - "--entrypoints.traefik.address=:8081"
    ports:
      - "8778:8080"
      - 8081:8081
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  api:
    depends_on:
      postgres:
        condition: service_healthy
    build: &build
      context: .
      args:
        SERVER_API_URL: http://api:3000
    restart: on-failure
    environment: &env
      - NODE_ENV=production
      - DATABASE_HINT=socket:/var/run/postgresql?db=remoteadminplus
      - SERVER_API_URL=http://api:3000
      - DATA_DIR=/data
    working_dir: /app/backend
    command: ["bun", "run", "start"]
    volumes:
      - app_data:/data
      - postgres-socket:/var/run/postgresql
    expose:
      - "3000"
    labels:
      - "traefik.http.routers.api.priority=100"
      - "traefik.http.routers.api.rule=PathPrefix(`/api`)"

  website:
    depends_on:
      api:
        condition: service_started
    build: *build
    restart: on-failure
    environment: *env
    working_dir: /app/website
    command: ["bun", "--bun", "./build"]
    expose:
      - "3000"
    labels:
      - "traefik.http.routers.website.rule=PathPrefix(`/`)"

volumes:
  postgres-data:
  app_data:
  postgres-socket:
